/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ClassementRouteImport } from './routes/classement'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedDisponibilitesRouteImport } from './routes/_authenticated/disponibilites'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCallbackRouteImport } from './routes/_authenticated/callback'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedActivitesRouteImport } from './routes/_authenticated/activites'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminStatistiquesRouteImport } from './routes/_authenticated/admin.statistiques'
import { Route as AuthenticatedAdminPaiementsRouteImport } from './routes/_authenticated/admin.paiements'
import { Route as AuthenticatedAdminGalerieRouteImport } from './routes/_authenticated/admin.galerie'
import { Route as AuthenticatedAdminEtudiantsRouteImport } from './routes/_authenticated/admin.etudiants'
import { Route as AuthenticatedAdminAnnoncesRouteImport } from './routes/_authenticated/admin.annonces'
import { Route as AuthenticatedAdminActivitesRouteImport } from './routes/_authenticated/admin.activites'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassementRoute = ClassementRouteImport.update({
  id: '/classement',
  path: '/classement',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDisponibilitesRoute =
  AuthenticatedDisponibilitesRouteImport.update({
    id: '/disponibilites',
    path: '/disponibilites',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCallbackRoute = AuthenticatedCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivitesRoute = AuthenticatedActivitesRouteImport.update({
  id: '/activites',
  path: '/activites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminStatistiquesRoute =
  AuthenticatedAdminStatistiquesRouteImport.update({
    id: '/statistiques',
    path: '/statistiques',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaiementsRoute =
  AuthenticatedAdminPaiementsRouteImport.update({
    id: '/paiements',
    path: '/paiements',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGalerieRoute =
  AuthenticatedAdminGalerieRouteImport.update({
    id: '/galerie',
    path: '/galerie',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEtudiantsRoute =
  AuthenticatedAdminEtudiantsRouteImport.update({
    id: '/etudiants',
    path: '/etudiants',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnnoncesRoute =
  AuthenticatedAdminAnnoncesRouteImport.update({
    id: '/annonces',
    path: '/annonces',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminActivitesRoute =
  AuthenticatedAdminActivitesRouteImport.update({
    id: '/activites',
    path: '/activites',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/classement': typeof ClassementRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/galerie': typeof GalerieRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/activites': typeof AuthenticatedActivitesRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/callback': typeof AuthenticatedCallbackRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/disponibilites': typeof AuthenticatedDisponibilitesRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/admin/activites': typeof AuthenticatedAdminActivitesRoute
  '/admin/annonces': typeof AuthenticatedAdminAnnoncesRoute
  '/admin/etudiants': typeof AuthenticatedAdminEtudiantsRoute
  '/admin/galerie': typeof AuthenticatedAdminGalerieRoute
  '/admin/paiements': typeof AuthenticatedAdminPaiementsRoute
  '/admin/statistiques': typeof AuthenticatedAdminStatistiquesRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/classement': typeof ClassementRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/galerie': typeof GalerieRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/activites': typeof AuthenticatedActivitesRoute
  '/callback': typeof AuthenticatedCallbackRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/disponibilites': typeof AuthenticatedDisponibilitesRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/admin/activites': typeof AuthenticatedAdminActivitesRoute
  '/admin/annonces': typeof AuthenticatedAdminAnnoncesRoute
  '/admin/etudiants': typeof AuthenticatedAdminEtudiantsRoute
  '/admin/galerie': typeof AuthenticatedAdminGalerieRoute
  '/admin/paiements': typeof AuthenticatedAdminPaiementsRoute
  '/admin/statistiques': typeof AuthenticatedAdminStatistiquesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/classement': typeof ClassementRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/galerie': typeof GalerieRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/activites': typeof AuthenticatedActivitesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/callback': typeof AuthenticatedCallbackRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/disponibilites': typeof AuthenticatedDisponibilitesRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/admin/activites': typeof AuthenticatedAdminActivitesRoute
  '/_authenticated/admin/annonces': typeof AuthenticatedAdminAnnoncesRoute
  '/_authenticated/admin/etudiants': typeof AuthenticatedAdminEtudiantsRoute
  '/_authenticated/admin/galerie': typeof AuthenticatedAdminGalerieRoute
  '/_authenticated/admin/paiements': typeof AuthenticatedAdminPaiementsRoute
  '/_authenticated/admin/statistiques': typeof AuthenticatedAdminStatistiquesRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth-callback'
    | '/classement'
    | '/forgot-password'
    | '/galerie'
    | '/reset-password'
    | '/sitemap.xml'
    | '/activites'
    | '/admin'
    | '/callback'
    | '/dashboard'
    | '/disponibilites'
    | '/profil'
    | '/admin/activites'
    | '/admin/annonces'
    | '/admin/etudiants'
    | '/admin/galerie'
    | '/admin/paiements'
    | '/admin/statistiques'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth-callback'
    | '/classement'
    | '/forgot-password'
    | '/galerie'
    | '/reset-password'
    | '/sitemap.xml'
    | '/activites'
    | '/callback'
    | '/dashboard'
    | '/disponibilites'
    | '/profil'
    | '/admin/activites'
    | '/admin/annonces'
    | '/admin/etudiants'
    | '/admin/galerie'
    | '/admin/paiements'
    | '/admin/statistiques'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/auth-callback'
    | '/classement'
    | '/forgot-password'
    | '/galerie'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/activites'
    | '/_authenticated/admin'
    | '/_authenticated/callback'
    | '/_authenticated/dashboard'
    | '/_authenticated/disponibilites'
    | '/_authenticated/profil'
    | '/_authenticated/admin/activites'
    | '/_authenticated/admin/annonces'
    | '/_authenticated/admin/etudiants'
    | '/_authenticated/admin/galerie'
    | '/_authenticated/admin/paiements'
    | '/_authenticated/admin/statistiques'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ClassementRoute: typeof ClassementRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GalerieRoute: typeof GalerieRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classement': {
      id: '/classement'
      path: '/classement'
      fullPath: '/classement'
      preLoaderRoute: typeof ClassementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/disponibilites': {
      id: '/_authenticated/disponibilites'
      path: '/disponibilites'
      fullPath: '/disponibilites'
      preLoaderRoute: typeof AuthenticatedDisponibilitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/callback': {
      id: '/_authenticated/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof AuthenticatedCallbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activites': {
      id: '/_authenticated/activites'
      path: '/activites'
      fullPath: '/activites'
      preLoaderRoute: typeof AuthenticatedActivitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/statistiques': {
      id: '/_authenticated/admin/statistiques'
      path: '/statistiques'
      fullPath: '/admin/statistiques'
      preLoaderRoute: typeof AuthenticatedAdminStatistiquesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/paiements': {
      id: '/_authenticated/admin/paiements'
      path: '/paiements'
      fullPath: '/admin/paiements'
      preLoaderRoute: typeof AuthenticatedAdminPaiementsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/galerie': {
      id: '/_authenticated/admin/galerie'
      path: '/galerie'
      fullPath: '/admin/galerie'
      preLoaderRoute: typeof AuthenticatedAdminGalerieRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/etudiants': {
      id: '/_authenticated/admin/etudiants'
      path: '/etudiants'
      fullPath: '/admin/etudiants'
      preLoaderRoute: typeof AuthenticatedAdminEtudiantsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/annonces': {
      id: '/_authenticated/admin/annonces'
      path: '/annonces'
      fullPath: '/admin/annonces'
      preLoaderRoute: typeof AuthenticatedAdminAnnoncesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/activites': {
      id: '/_authenticated/admin/activites'
      path: '/activites'
      fullPath: '/admin/activites'
      preLoaderRoute: typeof AuthenticatedAdminActivitesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminActivitesRoute: typeof AuthenticatedAdminActivitesRoute
  AuthenticatedAdminAnnoncesRoute: typeof AuthenticatedAdminAnnoncesRoute
  AuthenticatedAdminEtudiantsRoute: typeof AuthenticatedAdminEtudiantsRoute
  AuthenticatedAdminGalerieRoute: typeof AuthenticatedAdminGalerieRoute
  AuthenticatedAdminPaiementsRoute: typeof AuthenticatedAdminPaiementsRoute
  AuthenticatedAdminStatistiquesRoute: typeof AuthenticatedAdminStatistiquesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminActivitesRoute: AuthenticatedAdminActivitesRoute,
  AuthenticatedAdminAnnoncesRoute: AuthenticatedAdminAnnoncesRoute,
  AuthenticatedAdminEtudiantsRoute: AuthenticatedAdminEtudiantsRoute,
  AuthenticatedAdminGalerieRoute: AuthenticatedAdminGalerieRoute,
  AuthenticatedAdminPaiementsRoute: AuthenticatedAdminPaiementsRoute,
  AuthenticatedAdminStatistiquesRoute: AuthenticatedAdminStatistiquesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivitesRoute: typeof AuthenticatedActivitesRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCallbackRoute: typeof AuthenticatedCallbackRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDisponibilitesRoute: typeof AuthenticatedDisponibilitesRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivitesRoute: AuthenticatedActivitesRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCallbackRoute: AuthenticatedCallbackRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDisponibilitesRoute: AuthenticatedDisponibilitesRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ClassementRoute: ClassementRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GalerieRoute: GalerieRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
